name: running_on_dart
version: 3.3.3
description: Discord Bot for nyxx development
homepage: https://github.com/nyxx-discord/running_on_dart
repository: https://github.com/nyxx-discord/running_on_dart
documentation: https://github.com/nyxx-discord/running_on_dart
issue_tracker: https://github.com/nyxx-discord/running_on_dart/issues
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build_runner: ^2.4.6
  dynamic_config_generator: ^0.4.0
  envied: ^0.5.2
  http: ^1.1.1
  nyxx: ^6.0.2
  nyxx_commands:
    git:
      url: https://github.com/nyxx-discord/nyxx_commands.git
      ref: dev # branch name
  nyxx_extensions: ^4.1.0


dev_dependencies:
  lints: ^3.0.0
