name: running_on_dart
version: 3.3.3
description: Discord Bot for nyxx development
homepage: https://github.com/nyxx-discord/running_on_dart
repository: https://github.com/nyxx-discord/running_on_dart
documentation: https://github.com/nyxx-discord/running_on_dart
issue_tracker: https://github.com/nyxx-discord/running_on_dart/issues
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build_runner: ^2.4.6
  dart_openai: ^5.0.0
  fast_log: ^1.0.7
  http: ^1.1.2
  image: 3.0.1
  nyxx: ^6.0.3
  nyxx_commands: ^6.0.2
  nyxx_extensions: ^4.1.0
  toxic: ^1.0.3


dependency_overrides: # ...but downloads dependencies specified here
  nyxx:
    git:
      url: https://github.com/nyxx-discord/nyxx.git
      ref: dev
  lints: ^3.0.0
